2.0-pre
PolymerElements/iron-pages pull request #49
Opened 2016-09-13 17:55 UTC by bicknellr

2017-04-04 22:47 UTC, e111077 requested changes

2017-04-04 22:47 UTC, e111077 commented on iron-pages.html
>        :host > ::content > :not(.iron-selected) {
I believe that you can delete this in favor for the ::slotted one since contents are automatically switched to slots

2017-04-04 22:47 UTC, e111077 commented on test/basic.html
> +            pages.addEventListener('iron-items-changed', function onIronItemsChanged() {
why is this async now? Is this still necessary?

2017-04-04 22:47 UTC, e111077 commented on test/basic.html
> +            pages.addEventListener('iron-items-changed', function onIronItemsChanged() {
same question as above

2017-04-11 00:45 UTC, bicknellr commented on test/basic.html
> +            pages.addEventListener('iron-items-changed', function onIronItemsChanged() {
Same problem as mentioned in [this thread](https://github.com/PolymerElements/iron-selector/pull/139#discussion_r109078246) of iron-selector.

2017-04-11 00:45 UTC, bicknellr commented on test/basic.html
> +            pages.addEventListener('iron-items-changed', function onIronItemsChanged() {
(same answer)

2017-04-11 00:45 UTC, bicknellr commented on iron-pages.html
>        :host > ::content > :not(.iron-selected) {
:+1: will remove

2017-04-11 00:49 UTC, bicknellr commented on iron-pages.html
>        :host > ::content > :not(.iron-selected) {
removed

2017-04-11 01:07 UTC, e111077 commented on test/basic.html
> +            pages.addEventListener('iron-items-changed', function onIronItemsChanged() {
👍

2017-04-11 01:07 UTC, e111077 commented on test/basic.html
> +            pages.addEventListener('iron-items-changed', function onIronItemsChanged() {
👍

2017-04-11 01:11 UTC, e111077 approved these changes

2017-04-13 01:03 UTC, e111077 requested changes
please please pretty please can you add an example with `attr-for-selected`? it's a very common question despite it being in `iron-selector`

2017-04-13 23:13 UTC, bicknellr commented
@e111077 added!

2017-04-13 23:22 UTC, e111077 commented
double 👍 👍

2017-04-14 22:15 UTC, bicknellr commented
Any other changes?

2017-04-19 21:23 UTC, e111077 approved these changes

2017-05-12 21:19 UTC, merged